### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/csi-rclone#30]
Example specs to test in e2e tests:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: csi-rclone-example
type: Opaque
stringData:
  remote: giab
  remotePath: giab/
  configData: |
    [giab]
    type = s3
    provider = AWS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rclone-example
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rclone-tasko
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: myapp
    image: "debian:latest"
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: test-pvc
      mountPath: /giab
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: csi-rclone-example
---
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: csi-rclone-example-secret
type: Opaque
stringData:
  remote: giab
  remotePath: giab/
  configData: |
    [giab]
    type = s3
    provider = AWS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rclone-example
  annotations:
    csi-rclone.dev/secretName: csi-rclone-example-secret
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rclone-tasko-secret-annotation
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: myapp
    image: "debian:latest"
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: test-pvc
      mountPath: /giab
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: csi-rclone-example
---
```
