### ISSUE TITLE
postStart hooks that unmount rclone volumes can fail

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/csi-rclone#33]
The helm chart has this for the rclone container in the daemonset:

```yaml
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - mount -t fuse.rclone | while read -r mount; do umount $(echo $mount |
            awk {print $3}) ; done
```

This can be done as part of the code before the rclone container starts. So that if an error occurs it is easier to see and handle than the postStart hook which just causes the whole pod to restart when it fails.
 
Related to #27 where we want to be able to re-mount volumes when we have restarted.
