### ISSUE TITLE
Check if we can remove the preStop hook from the daemonset

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/csi-rclone#34]
This hook is on the node driver registrar on the daemonset.

I am not sure if this is standard practice or not. If it is (i.e. recomended by the docs for the `csi-node-driver-registrar:v2.12.0` sidecar then we leave it. If not we can do the same thing in code most likely.

```yaml
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - rm -rf /registration/csi-rclone /registration/csi-rclone-reg.sock
```
