### ISSUE TITLE
arm64 images

### ISSUE THREAD

**Issue by blampe** [SwissDataScienceCenter/csi-rclone#9]
https://hub.docker.com/r/renku/csi-rclone/tags currently only contains amd64.

**Comment by MeneDev** [comment]
I played around with nix a bit and came up with [that](https://github.com/MeneDev/csi-rclone) solution. I cannot get it to work nontheless, but the error message is different now.

You may try it out by setting the following chart parameters

```
parameters:
  - name: csiControllerRclone.rclone.image.repository
    value: menedev/csi-rclone
  - name: csiControllerRclone.rclone.image.tag
    value: 0.1.16
  - name: csiNodepluginRclone.rclone.image.repository
    value: menedev/csi-rclone
  - name: csiNodepluginRclone.rclone.image.tag
    value: 0.1.16
```

Don't get confused by the version tag, it's forked from fb889d0804bd7c3a317a093f0cf831bf15b48a64, so it's [v0.1.7](https://github.com/SwissDataScienceCenter/csi-rclone/releases/tag/v0.1.7).


The error message I'm getting is

```
Still connecting to unix:///plugin/csi.sock
```

deployed on microk8s v1.27.16
